project_id = "project-leafy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "leafy://auth"
additional_redirect_urls = ["leafy://auth"]
enable_signup = true

[functions.save-nutrition-plan]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.manage-data-contribution]
verify_jwt = false

[functions.discover-food-product]
verify_jwt = false

[functions.estimate-meal]
verify_jwt = false

[functions.transcribe-meal-audio]
verify_jwt = false

[functions.nutrition-chat]
verify_jwt = false

[functions.daily-nutrition]
verify_jwt = false

[functions.manage-food-entry]
verify_jwt = false
