import {
  nutrientCodes,
  nutrientUnits,
} from "../supabase/functions/_shared/nutrients.ts";

const outputPath = new URL(
  "../Leafy/Core/NutrientCatalog.generated.swift",
  import.meta.url,
);

const names: Record<string, string> = {
  carbohydrate_g: "Carbohydrate",
  fiber_g: "Dietary fiber",
  vitamin_a_mcg_rae: "Vitamin A",
  vitamin_c_mg: "Vitamin C",
  vitamin_d_mcg: "Vitamin D",
  vitamin_e_mg: "Vitamin E",
  vitamin_k_mcg: "Vitamin K",
  niacin_mg_ne: "Niacin",
  vitamin_b6_mg: "Vitamin B6",
  folate_mcg_dfe: "Folate",
  vitamin_b12_mcg: "Vitamin B12",
  pantothenic_acid_mg: "Pantothenic acid",
  linoleic_acid_g: "Linoleic acid (LA, omega-6)",
  alpha_linolenic_acid_g: "Alpha-linolenic acid (ALA, omega-3)",
  saturated_fat_g: "Saturated fat",
  added_sugars_g: "Added sugars",
  sugars_g: "Total sugars",
  trans_fat_g: "Trans fat",
};

const aminoAcids = new Set([
  "histidine_g",
  "isoleucine_g",
  "leucine_g",
  "lysine_g",
  "methionine_g",
  "phenylalanine_g",
  "threonine_g",
  "tryptophan_g",
  "valine_g",
]);
const vitamins = new Set(
  nutrientCodes.filter((code) => code.startsWith("vitamin_")).concat([
    "thiamin_mg",
    "riboflavin_mg",
    "niacin_mg_ne",
    "folate_mcg_dfe",
    "biotin_mcg",
    "pantothenic_acid_mg",
  ]),
);
const minerals = new Set([
  "calcium_mg",
  "iron_mg",
  "magnesium_mg",
  "phosphorus_mg",
  "iodine_mcg",
  "potassium_mg",
  "zinc_mg",
  "selenium_mcg",
  "copper_mg",
  "manganese_mg",
  "chromium_mcg",
  "molybdenum_mcg",
  "chloride_mg",
  "sulfur_mg",
  "sodium_mg",
]);
const limits = new Set(["saturated_fat_g", "added_sugars_g", "cholesterol_mg"]);

function title(code: string) {
  if (names[code]) return names[code];
  return code.replace(/_(mcg|mg|g)(?:_rae|_ne|_dfe)?$/, "").replaceAll("_", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function group(code: string) {
  if (["protein_g", "carbohydrate_g", "fat_g"].includes(code)) return "macros";
  if (code === "fiber_g") return "fiber";
  if (code === "choline_mg") return "choline";
  if (vitamins.has(code)) return "vitamins";
  if (minerals.has(code)) return "minerals";
  if (aminoAcids.has(code)) return "essentialAminoAcids";
  if (["linoleic_acid_g", "alpha_linolenic_acid_g"].includes(code)) {
    return "essentialFattyAcids";
  }
  if (limits.has(code)) return "limits";
  return "other";
}

const itemLines = nutrientCodes.map((code) =>
  `        .init(code: "${code}", name: "${title(code)}", unit: "${
    nutrientUnits[code]
  }", group: .${group(code)}),`
).join("\n");

const generated =
  `// Generated by scripts/generate-nutrient-catalog.ts. Do not edit.
import Foundation

enum NutrientCatalog {
    struct Item: Identifiable, Hashable, Sendable {
        let code: String
        let name: String
        let unit: String
        let group: NutritionGroup
        var id: String { code }
    }

    static let items: [Item] = [
${itemLines}
    ]

    private static let importanceRanks = Dictionary(
        uniqueKeysWithValues: items.enumerated().map { ($0.element.code, $0.offset) }
    )

    static func importanceRank(for code: String) -> Int {
        importanceRanks[code] ?? Int.max
    }

    static func items(in group: NutritionGroup) -> [Item] {
        items.filter { $0.group == group }.sorted {
            importanceRank(for: $0.code) < importanceRank(for: $1.code)
        }
    }
}
`;

if (Deno.args.includes("--check")) {
  const current = await Deno.readTextFile(outputPath).catch(() => "");
  if (current !== generated) {
    console.error(
      "Leafy/Core/NutrientCatalog.generated.swift is stale. Run the generator.",
    );
    Deno.exit(1);
  }
} else {
  await Deno.writeTextFile(outputPath, generated);
}
