// Generated by scripts/generate-nutrient-catalog.ts. Do not edit.
import Foundation

enum NutrientCatalog {
    struct Item: Identifiable, Hashable, Sendable {
        let code: String
        let name: String
        let unit: String
        let group: NutritionGroup
        var id: String { code }
    }

    static let items: [Item] = [
        .init(code: "protein_g", name: "Protein", unit: "g", group: .macros),
        .init(code: "carbohydrate_g", name: "Carbohydrate", unit: "g", group: .macros),
        .init(code: "fat_g", name: "Fat", unit: "g", group: .macros),
        .init(code: "fiber_g", name: "Dietary fiber", unit: "g", group: .fiber),
        .init(code: "sugars_g", name: "Total sugars", unit: "g", group: .other),
        .init(code: "added_sugars_g", name: "Added sugars", unit: "g", group: .limits),
        .init(code: "saturated_fat_g", name: "Saturated fat", unit: "g", group: .limits),
        .init(code: "trans_fat_g", name: "Trans fat", unit: "g", group: .other),
        .init(code: "cholesterol_mg", name: "Cholesterol", unit: "mg", group: .limits),
        .init(code: "sodium_mg", name: "Sodium", unit: "mg", group: .minerals),
        .init(code: "potassium_mg", name: "Potassium", unit: "mg", group: .minerals),
        .init(code: "calcium_mg", name: "Calcium", unit: "mg", group: .minerals),
        .init(code: "iron_mg", name: "Iron", unit: "mg", group: .minerals),
        .init(code: "magnesium_mg", name: "Magnesium", unit: "mg", group: .minerals),
        .init(code: "vitamin_d_mcg", name: "Vitamin D", unit: "mcg", group: .vitamins),
        .init(code: "vitamin_a_mcg_rae", name: "Vitamin A", unit: "mcg RAE", group: .vitamins),
        .init(code: "vitamin_c_mg", name: "Vitamin C", unit: "mg", group: .vitamins),
        .init(code: "vitamin_e_mg", name: "Vitamin E", unit: "mg", group: .vitamins),
        .init(code: "vitamin_k_mcg", name: "Vitamin K", unit: "mcg", group: .vitamins),
        .init(code: "thiamin_mg", name: "Thiamin", unit: "mg", group: .vitamins),
        .init(code: "riboflavin_mg", name: "Riboflavin", unit: "mg", group: .vitamins),
        .init(code: "niacin_mg_ne", name: "Niacin", unit: "mg NE", group: .vitamins),
        .init(code: "vitamin_b6_mg", name: "Vitamin B6", unit: "mg", group: .vitamins),
        .init(code: "folate_mcg_dfe", name: "Folate", unit: "mcg DFE", group: .vitamins),
        .init(code: "vitamin_b12_mcg", name: "Vitamin B12", unit: "mcg", group: .vitamins),
        .init(code: "biotin_mcg", name: "Biotin", unit: "mcg", group: .vitamins),
        .init(code: "pantothenic_acid_mg", name: "Pantothenic acid", unit: "mg", group: .vitamins),
        .init(code: "phosphorus_mg", name: "Phosphorus", unit: "mg", group: .minerals),
        .init(code: "iodine_mcg", name: "Iodine", unit: "mcg", group: .minerals),
        .init(code: "zinc_mg", name: "Zinc", unit: "mg", group: .minerals),
        .init(code: "selenium_mcg", name: "Selenium", unit: "mcg", group: .minerals),
        .init(code: "copper_mg", name: "Copper", unit: "mg", group: .minerals),
        .init(code: "manganese_mg", name: "Manganese", unit: "mg", group: .minerals),
        .init(code: "chromium_mcg", name: "Chromium", unit: "mcg", group: .minerals),
        .init(code: "molybdenum_mcg", name: "Molybdenum", unit: "mcg", group: .minerals),
        .init(code: "chloride_mg", name: "Chloride", unit: "mg", group: .minerals),
        .init(code: "choline_mg", name: "Choline", unit: "mg", group: .choline),
        .init(code: "caffeine_mg", name: "Caffeine", unit: "mg", group: .other),
        .init(code: "sulfur_mg", name: "Sulfur", unit: "mg", group: .minerals),
        .init(code: "histidine_g", name: "Histidine", unit: "g", group: .essentialAminoAcids),
        .init(code: "isoleucine_g", name: "Isoleucine", unit: "g", group: .essentialAminoAcids),
        .init(code: "leucine_g", name: "Leucine", unit: "g", group: .essentialAminoAcids),
        .init(code: "lysine_g", name: "Lysine", unit: "g", group: .essentialAminoAcids),
        .init(code: "methionine_g", name: "Methionine", unit: "g", group: .essentialAminoAcids),
        .init(code: "phenylalanine_g", name: "Phenylalanine", unit: "g", group: .essentialAminoAcids),
        .init(code: "threonine_g", name: "Threonine", unit: "g", group: .essentialAminoAcids),
        .init(code: "tryptophan_g", name: "Tryptophan", unit: "g", group: .essentialAminoAcids),
        .init(code: "valine_g", name: "Valine", unit: "g", group: .essentialAminoAcids),
        .init(code: "cystine_g", name: "Cystine", unit: "g", group: .other),
        .init(code: "tyrosine_g", name: "Tyrosine", unit: "g", group: .other),
        .init(code: "linoleic_acid_g", name: "Linoleic acid (LA, omega-6)", unit: "g", group: .essentialFattyAcids),
        .init(code: "alpha_linolenic_acid_g", name: "Alpha-linolenic acid (ALA, omega-3)", unit: "g", group: .essentialFattyAcids),
    ]

    private static let importanceRanks = Dictionary(
        uniqueKeysWithValues: items.enumerated().map { ($0.element.code, $0.offset) }
    )

    static func importanceRank(for code: String) -> Int {
        importanceRanks[code] ?? Int.max
    }

    static func items(in group: NutritionGroup) -> [Item] {
        items.filter { $0.group == group }.sorted {
            importanceRank(for: $0.code) < importanceRank(for: $1.code)
        }
    }
}
